// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: 5d8eb6c631324e0af0be0c0496bc08ee18cb62aea5b6f21abc00749b437b049e


/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "kwagga-theme";

export const themeNames: ThemeName[] = ["kwagga-theme"];

export type KcEnvName = never;

export const kcEnvNames: KcEnvName[] = [];

export const kcEnvDefaults: Record<KcEnvName, string> = {};

type KcContext =
    | import("./login/KcContext").KcContext
    | import("./account/KcContext").KcContext
    ;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));
export const KcAccountPage = lazy(() => import("./account/KcPage"));

export function KcPage(
    props: {
        kcContext: KcContext;
        fallback?: ReactNode;
    }
) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login": return <KcLoginPage kcContext={kcContext} />;
                    case "account": return <KcAccountPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}
